import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { api, loadConfig, lockSession, loginWithPassword, pageSession, queryClient, syncEntryVerification } from '../src/lib/api'

beforeEach(() => {
  pageSession.clear(); pageSession.setRequireEntryVerification(true); queryClient.clear()
  vi.stubGlobal('navigator', { sendBeacon: vi.fn(() => true) })
  vi.stubGlobal('document', { visibilityState: 'visible' })
})
afterEach(() => { pageSession.clear(); queryClient.clear(); vi.unstubAllGlobals() })
describe('locked API responses', () => {
  it('clears protected queries and rejects a response that completes after the page locks', async () => {
    pageSession.activate('a'.repeat(64), pageSession.epoch)
    queryClient.setQueryData(['workspace', 'test'], { subscriptions: ['private'] })
    queryClient.setQueryData(['config'], { authenticated: true, serverUrl: 'private-origin' })
    let complete!: (value: Response) => void
    const fetch = vi.fn((_input: RequestInfo | URL, _init?: RequestInit) => new Promise<Response>(resolve => { complete = resolve }))
    vi.stubGlobal('fetch', fetch)
    const pending = api('/workspace')
    expect(fetch.mock.calls[0][1]?.headers).toMatchObject({ 'x-page-session': 'a'.repeat(64) })
    lockSession()
    complete(Response.json({ subscriptions: ['old-private-data'] }))
    await expect(pending).rejects.toMatchObject({ name: 'AbortError' })
    expect(queryClient.getQueryData(['workspace', 'test'])).toBeUndefined()
    expect(queryClient.getQueryData(['config'])).toMatchObject({ authenticated: false, serverUrl: '' })
    expect(navigator.sendBeacon).toHaveBeenCalledOnce()
  })
  it('does not let an old 401 response lock a newer successful login', async () => {
    pageSession.activate('a'.repeat(64), pageSession.epoch)
    let complete!: (value: Response) => void
    vi.stubGlobal('fetch', vi.fn(() => new Promise<Response>(resolve => { complete = resolve })))
    const pending = api('/workspace')
    lockSession(); pageSession.activate('b'.repeat(64), pageSession.epoch)
    complete(Response.json({ error: 'expired' }, { status: 401 }))
    await expect(pending).rejects.toMatchObject({ name: 'AbortError' })
    expect(pageSession.token).toBe('b'.repeat(64))
  })
  it('revokes a late login result instead of restoring a closed page', async () => {
    let complete!: (value: Response) => void
    vi.stubGlobal('fetch', vi.fn(() => new Promise<Response>(resolve => { complete = resolve })))
    const pending = api('/login', { password: 'test-only-password' })
    lockSession(); complete(Response.json({ pageToken: 'a'.repeat(64) }))
    await expect(pending).rejects.toMatchObject({ name: 'AbortError' })
    expect(pageSession.unlocked).toBe(false)
    expect(navigator.sendBeacon).toHaveBeenCalledOnce()
  })
  it('loads the shared setting and uses the existing Cookie without storing a page token for a reopened page', async () => {
    const fetch = vi.fn(async (_url: string, _init?: RequestInit) => Response.json({ configured: true, authenticated: true, requireEntryVerification: false }))
    vi.stubGlobal('fetch', fetch)
    const config = await loadConfig()
    expect(config.authenticated).toBe(true); expect(pageSession.requireEntryVerification).toBe(false)
    expect(pageSession.token).toBe(null)
    expect(fetch.mock.calls[0][1]).toMatchObject({ credentials: 'same-origin', cache: 'no-store' })
    expect(fetch.mock.calls[0][1]?.headers).not.toHaveProperty('x-page-session')
  })
  it('clears resumed data when a synchronized setting requires verification again', () => {
    queryClient.setQueryData(['config'], { authenticated: true, requireEntryVerification: false, serverUrl: 'private-origin' })
    queryClient.setQueryData(['workspace', 'test'], { private: true })
    syncEntryVerification(true)
    expect(pageSession.requireEntryVerification).toBe(true)
    expect(queryClient.getQueryData(['config'])).toMatchObject({ authenticated: false, requireEntryVerification: true, serverUrl: '' })
    expect(queryClient.getQueryData(['workspace', 'test'])).toBeUndefined()
    expect(navigator.sendBeacon).not.toHaveBeenCalled()
  })
  it('clears resumed data on an expired Cookie response', async () => {
    syncEntryVerification(false)
    queryClient.setQueryData(['config'], { authenticated: true, requireEntryVerification: false, serverUrl: 'private-origin' })
    queryClient.setQueryData(['workspace', 'test'], { private: true })
    vi.stubGlobal('fetch', vi.fn(async () => Response.json({ error: '请先登录' }, { status: 401 })))
    await expect(api('/workspace')).rejects.toMatchObject({ status: 401 })
    expect(queryClient.getQueryData(['workspace', 'test'])).toBeUndefined()
    expect(queryClient.getQueryData(['config'])).toMatchObject({ authenticated: false })
  })
  it('finishes a config check after expiration and clears data before showing the login page', async () => {
    queryClient.setQueryData(['config'], { authenticated: true, requireEntryVerification: false })
    queryClient.setQueryData(['workspace', 'test'], { private: true })
    vi.stubGlobal('fetch', vi.fn(async () => Response.json({ authenticated: false, requireEntryVerification: false })))
    const config = await queryClient.fetchQuery({ queryKey: ['config'], queryFn: ({ signal }) => loadConfig(signal) })
    expect(config.authenticated).toBe(false)
    expect(queryClient.getQueryData(['workspace', 'test'])).toBeUndefined()
    expect(queryClient.getQueryData(['config'])).toMatchObject({ authenticated: false, requireEntryVerification: false })
  })
  it('accepts a requested password login completing in the background when entry verification is disabled', async () => {
    syncEntryVerification(false)
    vi.stubGlobal('document', { visibilityState: 'hidden' })
    vi.stubGlobal('fetch', vi.fn(async () => Response.json({ pageToken: 'a'.repeat(64) })))
    await loginWithPassword('test-password')
    expect(pageSession.token).toBe('a'.repeat(64))
    expect(navigator.sendBeacon).not.toHaveBeenCalled()
  })
})
